# Generated by Django 4.2.5 on 2023-10-03 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Streamer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitch_id', models.CharField(max_length=128, unique=True)),
                ('twitch_display_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='StreamInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('subject_name', models.CharField(max_length=140)),
                ('streamer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Api.streamer')),
            ],
        ),
    ]
